# 服务器端口
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#Minio配置
minio:
  endpoint: http://127.0.0.1:9090
  access-key: root
  secret-key: 12345678
  bucket-name: demo
  preview-expire: 3600 # 预览链接过期时间（秒，默认1小时）

# 服务端口
logging:
  level:
    org.example.mapper: debug
